import type { PracticeCompany } from "@webdev/types";

export const practiceCompanies: { id: PracticeCompany; label: string }[] = [
  { id: "google", label: "Google" },
  { id: "microsoft", label: "Microsoft" },
  { id: "amazon", label: "Amazon" },
  { id: "meta", label: "Meta" },
  { id: "netflix", label: "Netflix" },
  { id: "uber", label: "Uber" },
  { id: "flipkart", label: "Flipkart" },
  { id: "swiggy", label: "Swiggy" },
  { id: "zomato", label: "Zomato" },
  { id: "arcana", label: "Arcana" },
  { id: "rubrik", label: "Rubrik" },
];

export const companyOrder: Record<PracticeCompany, number> = Object.fromEntries(
  practiceCompanies.map((company, index) => [company.id, index]),
) as Record<PracticeCompany, number>;

/** Publicly reported frontend loops. A question can appear at more than one company. */
export const companyBySlug: Record<string, PracticeCompany[]> = {
  "reverse-string": ["google", "swiggy"],
  unique: ["google"],
  chunk: ["google"],
  flatten: ["google"],
  "make-counter": ["google"],
  compose: ["google"],
  palindrome: ["google", "swiggy"],
  anagram: ["google"],
  "valid-parens": ["google"],
  "two-sum": ["amazon", "google"],
  "flatten-deep": ["google"],
  "longest-unique-substring": ["google", "amazon"],
  "rotate-array": ["amazon"],
  "merge-sorted": ["google"],
  "max-subarray": ["amazon"],
  "get-path": ["google"],
  "flatten-object": ["google", "arcana"],
  "deep-clone": ["amazon", "google"],
  "deep-equal": ["google"],
  once: ["google"],
  pipe: ["google"],
  memoize: ["google", "amazon"],
  delay: ["google"],
  retry: ["microsoft", "uber", "google", "rubrik"],
  "curry-add": ["swiggy"],
  throttle: ["google", "microsoft", "uber", "swiggy"],
  debounce: ["google", "microsoft", "swiggy", "zomato", "uber", "flipkart", "arcana"],
  "timeout-promise": ["uber"],
  "sequential-map": ["swiggy"],
  "settle-all": ["google"],
  "parallel-limit": ["uber", "google"],
  "map-polyfill": ["swiggy"],
  "filter-polyfill": ["swiggy"],
  "reduce-polyfill": ["flipkart"],
  "flat-polyfill": ["google"],
  "call-polyfill": ["google", "microsoft"],
  "apply-polyfill": ["google", "microsoft"],
  "bind-polyfill": ["google", "microsoft", "swiggy"],
  "promise-all-polyfill": ["google", "microsoft"],
  "promise-race-polyfill": ["swiggy"],
  "promise-any-polyfill": ["swiggy"],
  "object-assign-polyfill": ["microsoft"],
  "event-emitter": ["google", "microsoft", "meta", "rubrik"],
  "custom-promise": ["google", "swiggy"],
  "json-stringify-polyfill": ["swiggy"],
  "event-delegation": ["google", "microsoft"],
  "get-by-class-name": ["google"],
  "render-virtual-dom": ["google"],
  "element-in-viewport": ["google"],
  "lazy-load-images": ["netflix", "amazon"],
  "highlight-search-text": ["google", "flipkart"],
  "click-outside-vanilla": ["microsoft"],
  "infinite-scroll-vanilla": ["swiggy", "zomato"],
  "find-corresponding-node": ["google"],
  "use-previous": ["google"],
  "use-window-size": ["google"],
  "use-debounce": ["google", "swiggy", "zomato", "arcana"],
  "use-local-storage": ["zomato"],
  "use-interval": ["zomato"],
  "use-click-outside": ["microsoft"],
  "use-fetch": ["zomato", "arcana", "rubrik"],
  "use-media-query": ["zomato"],
  "use-intersection-observer": ["zomato", "swiggy"],
  "todo-list": ["microsoft"],
  "star-rating": ["amazon", "flipkart"],
  "progress-bar": ["google"],
  accordion: ["amazon"],
  tabs: ["microsoft", "google"],
  "modal-dialog": ["microsoft", "zomato", "google"],
  pagination: ["microsoft", "swiggy", "arcana"],
  stopwatch: ["google"],
  "countdown-timer": ["swiggy"],
  "image-carousel": ["amazon", "flipkart", "rubrik"],
  "error-boundary": ["swiggy", "zomato"],
  "tic-tac-toe": ["google", "microsoft"],
  "form-validation": ["swiggy", "microsoft"],
  autocomplete: ["google", "swiggy", "zomato", "flipkart", "arcana"],
  "otp-input": ["swiggy"],
  "nested-comments": ["google", "meta"],
  "file-explorer": ["google"],
  "infinite-scroll-list": ["swiggy", "zomato", "meta", "netflix"],
  "virtualized-list": ["google", "swiggy", "zomato", "arcana", "netflix", "rubrik"],
  "data-table": ["microsoft", "arcana"],
  "reverse-integer": ["swiggy"],
  "longest-palindrome": ["swiggy"],
  "minesweeper-reveal": ["google"],
  "t9-type": ["microsoft"],
  "dynamic-html-table": ["google"],
  "html-outline": ["google"],
  "shopping-cart": ["swiggy", "flipkart"],
  "restaurant-search": ["zomato", "swiggy"],
  "poll-until": ["zomato", "uber"],
  "use-form": ["zomato"],
  "lru-cache": ["amazon", "google", "flipkart", "uber"],
  "nested-checkboxes": ["google"],
  "transfer-list": ["microsoft"],
  "analytics-queue": ["google"],
  "abort-search": ["flipkart", "google", "arcana"],
  "luhn-check": ["swiggy"],
  "prefix-trie": ["google", "flipkart", "amazon"],
  "with-loading": ["flipkart"],
  "retry-backoff": ["rubrik"],
  "throttle-promises": ["rubrik"],
  "carousel-controls": ["rubrik"],
  "responsive-app-shell": ["rubrik"],
  "use-cached-fetch": ["rubrik"],
  "shuffle-index": ["rubrik"],
  "grid-lights": ["meta", "google", "netflix", "amazon"],
  "like-button": ["meta"],
  "chips-input": ["google", "amazon", "swiggy"],
  "toast-stack": ["google", "microsoft"],
  "theme-context": ["flipkart", "zomato"],
  "favourites-catalog": ["microsoft"],
  "traffic-light": ["google"],
  "tic-tac-toe-n": ["google", "microsoft"],
  "product-grid": ["amazon", "flipkart"],
  "order-timeline": ["zomato", "swiggy", "uber"],
  "media-row": ["netflix"],
  "checkout-wizard": ["flipkart", "swiggy"],
  "jobs-board": ["rubrik", "amazon"],
  "timer-pause": ["rubrik", "swiggy", "amazon"],
  "poll-widget": ["google", "meta"],
  "use-online": ["uber"],
  "mini-store": ["flipkart", "uber"],
  "quantity-stepper": ["amazon", "swiggy"],
  "memory-pairs": ["amazon"],
};

export function companiesFor(slug: string): PracticeCompany[] {
  return companyBySlug[slug] ?? [];
}
