import type { PracticeQuestion } from "@webdev/types";

export const interviewQuestions: Omit<PracticeQuestion, "companies">[] = [
  {
    slug: "reverse-integer",
    title: "Reverse an integer",
    description: "Return the digits reversed. Drop the sign onto the result. Overflow becomes 0.",
    group: "basics",
    difficulty: "easy",
    fnName: "reverseInteger",
    signature: "reverseInteger(n) → number",
    prompt:
      "Implement reverseInteger(n). Reverse the decimal digits of n. Keep the sign. If the reversed value would not fit in a signed 32-bit integer (−2^31 … 2^31−1), return 0. Swiggy has used this as a JavaScript DSA screen.",
    examples: [
      { call: "reverseInteger(123)", result: "321" },
      { call: "reverseInteger(-120)", result: "-21" },
      { call: "reverseInteger(0)", result: "0" },
      { call: "reverseInteger(1534236469)", result: "0" },
    ],
    notes: [
      "Trailing zeros on the input disappear after reverse: 120 → 21.",
      "Do the overflow check after reversing, against 2147483647 and -2147483648.",
      "String reverse is fine; interviewers also accept the modulo loop.",
    ],
    hint: "const sign = n < 0 ? -1 : 1; const rev = Number(String(Math.abs(n)).split('').reverse().join(''));",
  },
  {
    slug: "longest-palindrome",
    title: "Longest palindromic substring",
    description: "Return the longest palindrome inside a string. Ties keep the leftmost.",
    group: "strings",
    difficulty: "hard",
    fnName: "longestPalindrome",
    signature: "longestPalindrome(s) → string",
    prompt:
      "Write longestPalindrome(s) that returns the longest palindromic substring of s. If several share that length, return the leftmost. Empty string returns empty. Reported on Swiggy frontend DSA rounds.",
    examples: [
      { call: 'longestPalindrome("babad")', result: '"bab"' },
      { call: 'longestPalindrome("cbbd")', result: '"bb"' },
      { call: 'longestPalindrome("a")', result: '"a"' },
      { call: 'longestPalindrome("ac")', result: '"a"' },
    ],
    notes: [
      "Expand around every centre — including the gap between two characters for even-length palindromes.",
      "There are 2n−1 centres in a string of length n.",
      "Manacher is overkill unless they ask for linear time.",
    ],
    hint: "For each i, expand (i,i) and (i,i+1) while s[L]===s[R]; keep the longest slice.",
  },
  {
    slug: "minesweeper-reveal",
    title: "Minesweeper reveal",
    description: "Click a cell: show a count, flood zeros, or hit a mine.",
    group: "arrays",
    difficulty: "hard",
    fnName: "reveal",
    signature: "reveal(board, click) → board",
    prompt:
      "board is a 2D array of 'M' (mine) and 'E' (hidden empty). reveal(board, [r, c]) mutates and returns it. Clicking a mine becomes 'X'. Clicking a cell with adjacent mines becomes that count as a string. Clicking a zero becomes 'B' and recursively reveals neighbors. Google has asked this as a frontend coding follow-up.",
    examples: [
      {
        call: 'reveal([["E","E","E"],["E","M","E"],["E","E","E"]], [0,0])',
        result: '[["B","1","E"],["1","M","E"],["E","E","E"]]',
      },
      { call: 'reveal([["E","M"]], [0,1])', result: '[["E","X"]]' },
    ],
    notes: [
      "Count mines in the eight neighbors before deciding to flood.",
      "Only flood from 'B' cells. Stop at numbered cells.",
      "Mutate in place; do not clone a new board unless they ask.",
    ],
    hint: "DFS/BFS from the click. If neighborMines>0 write the digit; else write 'B' and visit unseen 'E' neighbors.",
  },
  {
    slug: "t9-type",
    title: "T9 keypad typing",
    description: "Old flip-phone input: same key cycles letters until a pause.",
    group: "functions",
    difficulty: "hard",
    fnName: "t9Type",
    signature: "t9Type(presses, pauseMs) → string",
    prompt:
      "Simulate a T9 keypad. Keys: 2=abc, 3=def, 4=ghi, 5=jkl, 6=mno, 7=pqrs, 8=tuv, 9=wxyz. presses is { key, t }[] with timestamps. Pressing the same key again within pauseMs cycles the letter; waiting longer commits and starts a new character. A different key always commits. Microsoft has used this as a vanilla JS machine-coding problem.",
    examples: [
      { call: "t9Type([{key:'2',t:0}], 1000)", result: '"a"' },
      { call: "t9Type([{key:'2',t:0},{key:'2',t:100}], 1000)", result: '"b"' },
      { call: "t9Type([{key:'2',t:0},{key:'2',t:1100}], 1000)", result: '"aa"' },
      { call: "t9Type([{key:'2',t:0},{key:'6',t:50}], 1000)", result: '"am"' },
    ],
    notes: [
      "Wrap the cycle: three presses of 2 go a → b → c → a.",
      "7 and 9 have four letters.",
      "Ignore 0/1 or treat them as space only if the prompt says so — here they do not appear.",
    ],
    hint: "Track lastKey and lastTime. If same key and t-lastTime < pauseMs, replace the last char; else append.",
  },
  {
    slug: "dynamic-html-table",
    title: "Render a table from rows and columns",
    description: "A form that builds an HTML table of the given size.",
    group: "dom",
    difficulty: "medium",
    fnName: "renderTable",
    signature: "renderTable(root, rows, cols) → void",
    prompt:
      "renderTable(root, rows, cols) clears root and inserts a table with rows body rows and cols cells each. Header row optional — skip it. Cells can be empty. Google has asked candidates to wire two number inputs to this render.",
    examples: [
      { call: "renderTable(el, 2, 3)", result: "table with 2 tr, each with 3 td" },
      { call: "renderTable(el, 0, 4)", result: "empty table, no body rows" },
      { call: "renderTable(el, 1, 1)", result: "one cell" },
    ],
    notes: [
      "Use the table/tr/td APIs or innerHTML — either is fine if the structure is real table markup.",
      "Clear previous content so a second call replaces, not appends.",
      "Guard non-positive sizes: treat them as zero rows or columns.",
    ],
    hint: "root.replaceChildren(); const table = document.createElement('table'); nested loops append tr/td.",
  },
  {
    slug: "html-outline",
    title: "Document outline from headings",
    description: "Walk a DOM tree and return nested heading sections like a Google Doc outline.",
    group: "dom",
    difficulty: "medium",
    fnName: "htmlOutline",
    signature: "htmlOutline(root) → tree",
    prompt:
      "htmlOutline(root) DFS-walks root and builds a nested outline from h1–h6. Each node is { level, text, children }. A heading becomes a child of the nearest previous heading with a smaller level. Google has asked for a Google Doc outline view.",
    examples: [
      {
        call: "h1 A, h2 B, h2 C, h3 D",
        result: '[{level:1,text:"A",children:[{level:2,text:"B",children:[]},{level:2,text:"C",children:[{level:3,text:"D",children:[]}]}]}]',
      },
    ],
    notes: [
      "Use a stack of open nodes. Pop while stack.top.level >= next.level, then push under the new top.",
      "Ignore non-heading nodes except as containers to walk.",
      "text is textContent trimmed.",
    ],
    hint: "const stack = [{ level: 0, children: result }]; walk; on heading pop until level < h, then append and push.",
  },
  {
    slug: "lru-cache",
    title: "LRU cache",
    description: "O(1) get and put with least-recently-used eviction. A Map is enough in JS.",
    group: "objects",
    difficulty: "medium",
    fnName: "LRUCache",
    signature: "new LRUCache(capacity) → { get, put }",
    prompt:
      "Implement LRUCache(capacity) with get(key) and put(key, value). get returns the value or -1. Both get and put mark the key as most recently used. put evicts the least recently used key when the cache is full and the key is new. Flipkart, Amazon, Google, and Uber all use this on frontend loops.",
    examples: [
      { call: "c=LRUCache(2); c.put(1,1); c.put(2,2); c.get(1); c.put(3,3); c.get(2)", result: "get 1 → 1, get 2 → -1" },
      { call: "c.get(3)", result: "3" },
    ],
    notes: [
      "JavaScript Map is insertion-ordered. delete + set moves a key to the newest end.",
      "Evict Map.prototype.keys().next().value — that is the oldest.",
      "capacity 1 must still work. get on a missing key does not change order.",
    ],
    hint: "class { map = new Map(); get(k){ if(!map.has(k)) return -1; const v=map.get(k); map.delete(k); map.set(k,v); return v; } }",
  },
  {
    slug: "prefix-trie",
    title: "Prefix trie autocomplete",
    description: "Insert words, then return completions for a prefix.",
    group: "objects",
    difficulty: "hard",
    fnName: "Trie",
    signature: "new Trie() → { insert, complete }",
    prompt:
      "Implement a Trie with insert(word) and complete(prefix) returning all inserted words that start with prefix, sorted lexicographically. This is the data structure behind typeahead rounds at Google, Flipkart, and Amazon.",
    examples: [
      { call: 't.insert("apple"); t.insert("app"); t.insert("ape"); t.complete("ap")', result: '["ape","app","apple"]' },
      { call: 't.complete("b")', result: "[]" },
      { call: 't.complete("apple")', result: '["apple"]' },
    ],
    notes: [
      "Each node is { children: Map, isWord: boolean }.",
      "Walk the prefix, then DFS or BFS to collect words.",
      "Do not scan a flat word list — they will ask why a trie is O(prefix + matches).",
    ],
    hint: "Walk prefix to a node, then recurse children accumulating the path; push when isWord.",
  },
  {
    slug: "poll-until",
    title: "Poll until ready",
    description: "Call an async fn on an interval until it succeeds, fails, or times out.",
    group: "async",
    difficulty: "medium",
    fnName: "pollUntil",
    signature: "pollUntil(fn, { interval, timeout }) → Promise",
    prompt:
      "pollUntil(fn, { interval, timeout }) calls fn immediately, then every interval ms, until fn resolves to a truthy value, rejects, or timeout ms have passed. Resolve with that value. Reject on timeout or if fn rejects. Zomato and Uber discuss this as the HTTP alternative to a WebSocket order tracker.",
    examples: [
      { call: "fn resolves truthy on 3rd tick, interval 50, timeout 1000", result: "resolves that value" },
      { call: "fn always null, timeout 100", result: "rejects" },
      { call: "fn rejects", result: "rejects with that error" },
    ],
    notes: [
      "Clear the interval on settle so tests and pages do not leak timers.",
      "Do not overlap in-flight calls — wait for the previous fn to finish.",
      "timeout is wall-clock from start, not a retry count.",
    ],
    hint: "new Promise((resolve, reject) => { const start=Date.now(); const tick=async()=>{...}; tick(); })",
  },
  {
    slug: "abort-search",
    title: "Abort in-flight search",
    description: "Drop stale responses so a slower older query cannot overwrite a newer one.",
    group: "async",
    difficulty: "medium",
    fnName: "searchLatest",
    signature: "searchLatest(query, fetchFn) → Promise",
    prompt:
      "searchLatest(query, fetchFn) calls fetchFn(query, { signal }) and returns its result. A newer call aborts the previous one via AbortController. Ignore AbortError from the stale call. Flipkart search, Google typeahead, and Arcana filter UIs all fail this race without cancellation.",
    examples: [
      { call: 'searchLatest("a"); searchLatest("ab")', result: "only ab's response is used" },
      { call: "stale fetch rejects AbortError", result: "not thrown to the caller of the old promise" },
    ],
    notes: [
      "Keep one controller in a closure. abort() it at the start of every new search, then make a new controller.",
      "Pass signal into fetchFn. fetch() already understands it.",
      "Do not treat AbortError as a user-facing failure for the superseded query.",
    ],
    hint: "let controller; return (q) => { controller?.abort(); controller = new AbortController(); return fetchFn(q, { signal: controller.signal }); }",
  },
  {
    slug: "analytics-queue",
    title: "Analytics event queue",
    description: "Batch page events and flush on size, interval, or page hide.",
    group: "functions",
    difficulty: "hard",
    fnName: "createTracker",
    signature: "createTracker({ send, max, interval }) → { track, flush }",
    prompt:
      "createTracker({ send, max, interval }) returns track(event) and flush(). Events sit in a queue. Flush when the queue hits max, every interval ms if anything is pending, or when the page fires visibilitychange to hidden. send(batch) is async; do not lose events if it fails — put them back. Google has asked for a tiny Analytics SDK with this shape.",
    examples: [
      { call: "max 3; track a,b,c", result: "send([a,b,c])" },
      { call: "track a; wait interval", result: "send([a])" },
      { call: "send rejects", result: "events re-queued" },
    ],
    notes: [
      "visibilitychange + document.hidden is the modern replacement for unload beacons in a kata.",
      "Copy the batch out, clear the queue, send, and on failure unshift them back.",
      "flush should be idempotent when the queue is empty.",
    ],
    hint: "queue=[]; const flush=async()=>{ const batch=queue.splice(0); try{ await send(batch) } catch{ queue.unshift(...batch) } };",
  },
  {
    slug: "luhn-check",
    title: "Luhn card-number check",
    description: "Validate a payment-card number. Swiggy payment-form rounds use this.",
    group: "strings",
    difficulty: "easy",
    fnName: "luhnCheck",
    signature: "luhnCheck(number) → boolean",
    prompt:
      "luhnCheck(number) accepts a string of digits (spaces allowed) and returns whether it passes the Luhn checksum. Double every second digit from the right; if doubling exceeds 9, subtract 9; the total must be divisible by 10.",
    examples: [
      { call: 'luhnCheck("4539578763621486")', result: "true" },
      { call: 'luhnCheck("4539 5787 6362 1486")', result: "true" },
      { call: 'luhnCheck("1234567890123456")', result: "false" },
    ],
    notes: [
      "Strip whitespace first. Reject any remaining non-digit.",
      "Walk from the end so 'every second digit' does not depend on length parity.",
    ],
    hint: "digits reverse; map (d,i) => i%2 ? (d*2>9?d*2-9:d*2) : d; sum % 10 === 0.",
  },
  {
    slug: "shopping-cart",
    title: "Shopping cart",
    description: "Add, change quantity, remove, and keep a live total — Swiggy / Flipkart machine coding.",
    group: "react",
    difficulty: "medium",
    fnName: "ShoppingCart",
    signature: "<ShoppingCart catalog /> → cart with totals",
    prompt:
      "Build ShoppingCart given a catalog of { id, name, price, stock }. The user can add an item (no more than stock), bump quantity, remove a line, and see subtotal. Out-of-stock items cannot be added. Swiggy and Flipkart both use a cart as the machine-coding round.",
    examples: [
      { call: "add Milk twice", result: "one line, qty 2, subtotal 2×price" },
      { call: "qty would exceed stock", result: "stays at stock" },
      { call: "remove the line", result: "subtotal 0" },
    ],
    notes: [
      "Store cart as a map of id → qty, not duplicated rows.",
      "Derive lines and total from catalog + qty; do not keep a redundant price copy unless they ask for price-at-add-time.",
      "Disable Add when qty === stock.",
    ],
    hint: "const [qty, setQty] = useState({}); add = (id) => setQty(q => ({...q, [id]: Math.min(stock, (q[id]??0)+1)}))",
  },
  {
    slug: "restaurant-search",
    title: "Restaurant search and filters",
    description: "Search by name, filter cuisine and rating, sort. Zomato / Swiggy UI round.",
    group: "react",
    difficulty: "medium",
    fnName: "RestaurantSearch",
    signature: "<RestaurantSearch restaurants /> → search, filter, sort",
    prompt:
      "RestaurantSearch receives restaurants: { id, name, cuisine, rating, etaMinutes }[]. Provide a search box (case-insensitive name match), cuisine chips, a minimum-rating filter, and sort by rating or ETA. Show an empty state when nothing matches. Zomato and Swiggy restaurant-list rounds look like this.",
    examples: [
      { call: 'type "biryani"', result: "names containing biryani" },
      { call: "min rating 4, cuisine Indian", result: "intersection of both" },
      { call: "sort ETA", result: "ascending etaMinutes" },
    ],
    notes: [
      "Derive the visible list with useMemo from query + filters + sort. Do not store a second array in state.",
      "Debounce the search box if they ask — reuse the debounce kata.",
      "Reset paging if you add it later; this kata can stay as a single list.",
    ],
    hint: "visible = restaurants.filter(name).filter(cuisine).filter(rating).sort(compare)",
  },
  {
    slug: "use-form",
    title: "useForm hook",
    description: "Values, errors, and a validator — Zomato SDE-2 hook-from-scratch.",
    group: "react",
    difficulty: "medium",
    fnName: "useForm",
    signature: "useForm({ initial, validate }) → { values, errors, onChange, handleSubmit }",
    prompt:
      "Implement useForm({ initial, validate }). values start as initial. onChange(name, value) patches one field and clears that field's error. handleSubmit(onValid) runs validate(values); if it returns an errors object with any keys, set errors and skip onValid; otherwise call onValid(values). Zomato has asked this live.",
    examples: [
      { call: "onChange('email','a@b.c')", result: "values.email is a@b.c" },
      { call: "validate returns { email: 'required' }", result: "handleSubmit does not call onValid" },
      { call: "validate returns {}", result: "onValid(values)" },
    ],
    notes: [
      "validate is a pure function of values, not an async schema — unless they extend the prompt.",
      "Do not mutate initial. Copy it into useState.",
      "Clear only the field that changed so other errors remain until the next submit.",
    ],
    hint: "const [values,setValues]=useState(initial); const onChange=(name,value)=>{ setValues(v=>({...v,[name]:value})); setErrors(e=>{ const n={...e}; delete n[name]; return n; }); }",
  },
  {
    slug: "nested-checkboxes",
    title: "Nested checkboxes",
    description: "Parent reflects children: all, none, or indeterminate. Google UI staple.",
    group: "react",
    difficulty: "hard",
    fnName: "NestedCheckboxes",
    signature: "<NestedCheckboxes tree /> → cascading checks",
    prompt:
      "Render a tree of { id, label, children? }. Checking a parent checks all descendants. Checking all children checks the parent. A mixed parent is indeterminate. Google asks this often as a permissions / label-picker widget.",
    examples: [
      { call: "check parent", result: "every descendant checked" },
      { call: "uncheck one child", result: "parent is indeterminate" },
      { call: "check the last unchecked child", result: "parent checked" },
    ],
    notes: [
      "Keep a Set of checked ids. Derive parent state from children — do not store it separately.",
      "indeterminate is a DOM property on the input, not an HTML attribute. Set it in an effect or ref callback.",
      "Walk the tree once to collect descendant ids when a parent toggles.",
    ],
    hint: "function status(node): 'all'|'none'|'mixed' from children; toggle(node, checked) writes all descendant ids.",
  },
  {
    slug: "transfer-list",
    title: "Transfer list",
    description: "Two lists with move selected / move all. Microsoft Fluent-style widget.",
    group: "react",
    difficulty: "medium",
    fnName: "TransferList",
    signature: "<TransferList items /> → left/right shuttle",
    prompt:
      "TransferList starts with items on the left. The user selects rows (multi-select), then moves selected or all to the other side. Preserve original order inside each list. Microsoft has used this as a React machine-coding problem.",
    examples: [
      { call: "select A,C and move right", result: "left missing A,C; right has them in original order" },
      { call: "move all left", result: "right empty" },
    ],
    notes: [
      "Store leftIds and rightIds plus a selected Set. Items stay in a dictionary by id.",
      "Disable Move when nothing selected on that side.",
      "Keyboard: Space toggles selection if you have time.",
    ],
    hint: "move = (from, to, onlySelected) => { const take = onlySelected ? from.filter(id => selected.has(id)) : from; ... }",
  },
  {
    slug: "with-loading",
    title: "withLoading HOC",
    description: "Wrap a component to show a spinner while a flag is true. Flipkart UI-tech.",
    group: "react",
    difficulty: "medium",
    fnName: "withLoading",
    signature: "withLoading(Component) → (props & { loading }) => element",
    prompt:
      "withLoading(Component) returns a component that renders a loading indicator when props.loading is true, otherwise <Component {...rest} />. Do not pass loading through to Component. Flipkart has asked candidates to live-code an HOC after a vanilla round.",
    examples: [
      { call: "loading true", result: "spinner (or 'Loading'), Component unmounted" },
      { call: "loading false", result: "Component receives the remaining props" },
    ],
    notes: [
      "Copy a displayName: `WithLoading(${Component.displayName || Component.name})`.",
      "This is an HOC, not a hook. They may ask when a wrapper component is clearer.",
      "Keep the spinner accessible: role=\"status\" and live text.",
    ],
    hint: "function withLoading(Component) { function Wrapped({ loading, ...props }) { return loading ? <Status /> : <Component {...props} />; } return Wrapped; }",
  },
  {
    slug: "retry-backoff",
    title: "Retry a promise with backoff",
    description: "Auto-retry a failing async call, waiting longer between attempts.",
    group: "async",
    difficulty: "hard",
    fnName: "retryWithBackoff",
    signature: "retryWithBackoff(task, { retries, baseDelay }) → Promise",
    prompt:
      "Implement retryWithBackoff(task, { retries, baseDelay }). Call task() immediately. On throw or reject, wait baseDelay * 2^attempt milliseconds, then try again. retries is extra attempts after the first call (retries: 3 means four calls max). Resolve with the first success. If every attempt fails, rethrow the last error. Rubrik’s UI JavaScript round has asked for auto-retry promises in this shape.",
    examples: [
      { call: "task succeeds first try", result: "resolves immediately, no delay" },
      { call: "fails, then succeeds; baseDelay 100", result: "waits ~100ms, then resolves" },
      { call: "retries 2, always fails", result: "three calls, then rejects with the last error" },
    ],
    notes: [
      "Do not sleep after the final failure — throw instead.",
      "Interviewers often follow up with jitter (randomize the delay) so retries do not stampede.",
      "The existing retry kata has no delay; this one is the production client version.",
    ],
    hint: "for (let i = 0;; i++) { try { return await task(); } catch (e) { if (i >= retries) throw e; await sleep(baseDelay * 2 ** i); } }",
  },
  {
    slug: "throttle-promises",
    title: "Throttle promises by batching",
    description: "Run async tasks in batches of N; wait for a batch to finish before starting the next.",
    group: "async",
    difficulty: "hard",
    fnName: "throttlePromises",
    signature: "throttlePromises(tasks, batchSize) → Promise<array>",
    prompt:
      "throttlePromises(tasks, batchSize) takes an array of functions that return promises. Run them in chunks of batchSize: start a whole batch, await Promise.all, then start the next chunk. Resolve with results in the original task order. Empty input resolves to []. This is the second JavaScript problem from Rubrik’s UI screen — distinct from a sliding concurrency pool, which starts the next task as soon as any slot frees.",
    examples: [
      { call: "three tasks, batchSize 2", result: "first two overlap; the third starts after both settle" },
      { call: "await throttlePromises([], 2)", result: "[]" },
      { call: "batchSize 1", result: "strictly sequential" },
    ],
    notes: [
      "Slice tasks with a for-loop stepping by batchSize. Do not start task i+batchSize until the current Promise.all settles.",
      "If one task in a batch rejects, Promise.all rejects — that is expected unless they ask for settle.",
      "Write results with push(...await Promise.all(chunk.map((fn) => fn()))) so order stays stable.",
    ],
    hint: "const out = []; for (let i = 0; i < tasks.length; i += batchSize) { out.push(...await Promise.all(tasks.slice(i, i + batchSize).map((fn) => fn()))); } return out;",
  },
  {
    slug: "shuffle-index",
    title: "Shuffle to a different slide",
    description: "Pick a new random index that is not the current one.",
    group: "basics",
    difficulty: "easy",
    fnName: "nextShuffleIndex",
    signature: "nextShuffleIndex(length, current) → number",
    prompt:
      "nextShuffleIndex(length, current) returns a random integer in [0, length). If length > 1 it must not equal current — Rubrik’s carousel round rejected candidates who shuffled onto the same slide. length 0 returns 0. length 1 always returns 0.",
    examples: [
      { call: "nextShuffleIndex(1, 0)", result: "0" },
      { call: "nextShuffleIndex(0, 0)", result: "0" },
      { call: "nextShuffleIndex(5, 2) many times", result: "values in 0..4, never 2" },
    ],
    notes: [
      "Rejection-sample: pick Math.floor(Math.random() * length) until it differs, or map a roll in [0, length-1) onto the other indices.",
      "Do not mutate an images array to shuffle — only the index (or a copy) should change.",
      "Math.random() * length can still land on current; that is the edge case they graded.",
    ],
    hint: "if (length <= 1) return 0; let i; do { i = Math.floor(Math.random() * length); } while (i === current); return i;",
  },
  {
    slug: "carousel-controls",
    title: "Carousel with shuffle and jump",
    description: "Reusable React carousel: circular prev/next, first, last, shuffle, and motion.",
    group: "react",
    difficulty: "hard",
    fnName: "ControlledCarousel",
    signature: "<ControlledCarousel images /> → prev, next, first, last, shuffle",
    prompt:
      "Build a reusable ControlledCarousel({ images }) showing one slide at a time. Wire Previous, Next, First, Last, and Shuffle. Prev/next wrap (circular). First jumps to 0, Last to length-1. Shuffle picks a different index when there is more than one image (do not stay on the same slide). Disable controls that cannot move when there are 0–1 images. Add a CSS transition on the slide change. Rubrik’s UI coding round is this widget — interviewers failed people on shuffle edge cases and weak CSS.",
    examples: [
      { call: "Next on the last slide", result: "index 0" },
      { call: "Previous on the first slide", result: "last index" },
      { call: "Shuffle with 5 images at index 2", result: "some index other than 2" },
      { call: "Shuffle with 1 image", result: "stays at 0; control disabled or no-op" },
    ],
    notes: [
      "Keep images as a prop. Shuffle the index, not the source array, unless they ask to reorder.",
      "Empty images: render a placeholder, do not crash on % 0.",
      "Name buttons accessibly. Animate with transform/opacity, not a layout jump.",
    ],
    hint: "Wrap with (i ± 1 + n) % n. Shuffle: sample until !== current when n > 1. First/Last set 0 and n-1.",
  },
  {
    slug: "responsive-app-shell",
    title: "Responsive app shell from a wireframe",
    description: "Header, collapsible nav, main, footer — flex/grid plus a JS menu toggle.",
    group: "dom",
    difficulty: "medium",
    fnName: "renderAppShell",
    signature: "renderAppShell(root) → void",
    prompt:
      "renderAppShell(root) paints a small app chrome from a wireframe: a header with a title and a menu button, a nav, a main landmark, and a footer. On a wide viewport the nav sits in a sidebar. On a narrow viewport the nav is hidden until the menu button toggles it (aria-expanded must track state). Use flex or grid and a media query or matchMedia — do not only restyle with JavaScript. Rubrik has given frontend candidates a wireframe and asked for a working responsive page with event handling.",
    examples: [
      { call: "renderAppShell(el)", result: "header, nav, main, footer inside el" },
      { call: "click menu when narrow", result: "nav visible, button aria-expanded true" },
      { call: "click again", result: "nav hidden, aria-expanded false" },
    ],
    notes: [
      "Use real landmarks: header, nav, main, footer. The menu button needs an accessible name.",
      "Closing the menu when the viewport grows is a nice follow-up.",
      "They will ask Grid vs Flexbox: flex for the header row and stacking; grid if the sidebar + main need aligned columns.",
    ],
    hint: "root.innerHTML = shell markup; button.onclick toggles a class on nav and aria-expanded. CSS @media (min-width) shows nav as a column.",
  },
  {
    slug: "use-cached-fetch",
    title: "useCachedFetch",
    description: "Data-fetching hook with an in-memory cache and in-flight dedupe.",
    group: "react",
    difficulty: "hard",
    fnName: "useCachedFetch",
    signature: "useCachedFetch(url) → { data, error, loading, refetch }",
    prompt:
      "Write useCachedFetch(url) that returns { data, error, loading, refetch }. Cache successful JSON by url so remounting with the same url can show data immediately. If two components request the same in-flight url, share one fetch (dedupe). refetch bypasses the cache. Abort on unmount or url change. Rubrik frontend screens discuss a custom hook for fetching plus caching — this is that hook.",
    examples: [
      { call: "first mount /api/a", result: "loading, then data; cache stores it" },
      { call: "second mount /api/a", result: "data from cache, loading false (or brief revalidate)" },
      { call: "refetch()", result: "hits the network again and updates the cache" },
    ],
    notes: [
      "A module-level Map<url, { data } | Promise> is enough. Do not put the cache in React state.",
      "Still abort the consumer’s interest on unmount; the shared promise can keep running for others.",
      "Treat AbortError as non-error for the unmounted caller.",
    ],
    hint: "const cache = new Map(); const inflight = new Map(); if (cache.has(url)) return cached; if (!inflight.has(url)) inflight.set(url, fetch(url).then(store));",
  },
];
