import type { LucideIcon } from "lucide-react";
import {
  ArrowUpDown,
  Binary,
  Braces,
  Calculator,
  CalendarClock,
  Clock,
  Fingerprint,
  GitCompare,
  Globe,
  HardDrive,
  Hash,
  KeyRound,
  Link2,
  ListOrdered,
  Lock,
  Palette,
  Regex,
  Server,
  Shield,
  Table2,
  TextCursorInput,
  Type,
  Code2,
} from "lucide-react";

export const toolIcons: Record<string, LucideIcon> = {
  json: Braces,
  base64: Binary,
  "url-encode": Link2,
  "html-entities": Code2,
  jwt: KeyRound,
  uuid: Fingerprint,
  hash: Hash,
  timestamp: Clock,
  regex: Regex,
  color: Palette,
  case: Type,
  slugify: TextCursorInput,
  diff: GitCompare,
  "csv-json": Table2,
  password: Lock,
  bytes: HardDrive,
  semver: ArrowUpDown,
  cron: CalendarClock,
  "number-base": Calculator,
  "url-inspect": Globe,
  lines: ListOrdered,
  chmod: Shield,
  "http-status": Server,
};
